version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/grouproom
      - REDIS_URL=redis://redis:6379
      - DEFAULT_EXPIRY_MINUTES=30
      - PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: ["npm","run","dev"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grouproom
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
